spring.application.name=codersbank
spring.datasource.url=jdbc:postgresql://localhost:5432/codersbank
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
jwt.secret=sadakdkajdkahskdjahkahlkdhahdakhsd@@EDAda2
spring.security.user.name=admin
spring.security.user.password=admin123